// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4PBBU8D0DTJuN0f2E5SWjjDqI7MLsCY',
    appId: '1:218379717523:web:ffe6687ae2ac0e820b7666',
    messagingSenderId: '218379717523',
    projectId: 'chat-cubit-5a5dc',
    authDomain: 'chat-cubit-5a5dc.firebaseapp.com',
    storageBucket: 'chat-cubit-5a5dc.appspot.com',
    measurementId: 'G-17BJKK0XGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNI1Lf62ddeWP9mUguu3spEbUrkFLTvl8',
    appId: '1:218379717523:android:bbede86223e8181e0b7666',
    messagingSenderId: '218379717523',
    projectId: 'chat-cubit-5a5dc',
    storageBucket: 'chat-cubit-5a5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ziPwB3B4XULl9R38koKJOCQnOmUAPIc',
    appId: '1:218379717523:ios:b3954705dde1c9890b7666',
    messagingSenderId: '218379717523',
    projectId: 'chat-cubit-5a5dc',
    storageBucket: 'chat-cubit-5a5dc.appspot.com',
    iosClientId: '218379717523-vsch4qo0crspoqoks269sp0olbtuni78.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ziPwB3B4XULl9R38koKJOCQnOmUAPIc',
    appId: '1:218379717523:ios:7180148c260462790b7666',
    messagingSenderId: '218379717523',
    projectId: 'chat-cubit-5a5dc',
    storageBucket: 'chat-cubit-5a5dc.appspot.com',
    iosClientId: '218379717523-4agaq6a05bjfntsdgh92bi7fh2rfng1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
